/*
  Warnings:

  - You are about to drop the column `promedioIngresosMensuales` on the `DatosSociodemograficos` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Colaboradores" ALTER COLUMN "activo" DROP NOT NULL,
ALTER COLUMN "area" DROP NOT NULL,
ALTER COLUMN "cargo" DROP NOT NULL,
ALTER COLUMN "celular" DROP NOT NULL,
ALTER COLUMN "correo" DROP NOT NULL,
ALTER COLUMN "direccion" DROP NOT NULL,
ALTER COLUMN "escolaridad" DROP NOT NULL,
ALTER COLUMN "experienciaAnos" DROP NOT NULL,
ALTER COLUMN "fechaIngreso" DROP NOT NULL,
ALTER COLUMN "fechaNacimiento" DROP NOT NULL,
ALTER COLUMN "formaPago" DROP NOT NULL,
ALTER COLUMN "genero" DROP NOT NULL,
ALTER COLUMN "horasMensualesContratadas" DROP NOT NULL,
ALTER COLUMN "profesion" DROP NOT NULL,
ALTER COLUMN "riesgoARL" DROP NOT NULL,
ALTER COLUMN "salarioBase" DROP NOT NULL,
ALTER COLUMN "telefonoFijo" DROP NOT NULL,
ALTER COLUMN "tipoContrato" DROP NOT NULL;

-- AlterTable
ALTER TABLE "DatosSociodemograficos" DROP COLUMN "promedioIngresosMensuales",
ALTER COLUMN "estadoCivil" DROP NOT NULL,
ALTER COLUMN "estratoSocioeconomico" DROP NOT NULL,
ALTER COLUMN "tipoVivienda" DROP NOT NULL,
ALTER COLUMN "grupoSanguineo" DROP NOT NULL,
ALTER COLUMN "enfermedadesDiagnosticadasPermanentes" DROP NOT NULL,
ALTER COLUMN "medicamentoRecetadoPermanente" DROP NOT NULL,
ALTER COLUMN "fuma" DROP NOT NULL,
ALTER COLUMN "consumeBebidasAlcoholicas" DROP NOT NULL,
ALTER COLUMN "consumeBebidasEnergeticasConstantemente" DROP NOT NULL,
ALTER COLUMN "practicaDeportivaRegular" DROP NOT NULL,
ALTER COLUMN "otroTrabajo" DROP NOT NULL,
ALTER COLUMN "laboresDomesticas" DROP NOT NULL,
ALTER COLUMN "recreacionDeporte" DROP NOT NULL,
ALTER COLUMN "estudio" DROP NOT NULL,
ALTER COLUMN "otraActividad" DROP NOT NULL,
ALTER COLUMN "vacunacion" DROP NOT NULL,
ALTER COLUMN "saludOral" DROP NOT NULL,
ALTER COLUMN "valoracionMedicoOcupacional" DROP NOT NULL,
ALTER COLUMN "examenesLaboratorio" DROP NOT NULL,
ALTER COLUMN "spaRelajacionSimilar" DROP NOT NULL,
ALTER COLUMN "actividadesSST" DROP NOT NULL,
ALTER COLUMN "ninguna" DROP NOT NULL,
ALTER COLUMN "cantidadDosisCovid19" DROP NOT NULL,
ALTER COLUMN "tieneHijos" DROP NOT NULL,
ALTER COLUMN "personasNucleoFamiliar" DROP NOT NULL,
ALTER COLUMN "personasDependientesEconomicamente" DROP NOT NULL,
ALTER COLUMN "eps" DROP NOT NULL,
ALTER COLUMN "fondoPension" DROP NOT NULL,
ALTER COLUMN "arl" DROP NOT NULL,
ALTER COLUMN "nombreContactoEmergencia" DROP NOT NULL,
ALTER COLUMN "telefonoContactoEmergencia" DROP NOT NULL,
ALTER COLUMN "parentescoContactoEmergencia" DROP NOT NULL;

-- AlterTable
ALTER TABLE "JornadasLaborales" ALTER COLUMN "diaJornada" DROP NOT NULL,
ALTER COLUMN "festivo" DROP NOT NULL,
ALTER COLUMN "horaProgramadaEntrada" DROP NOT NULL,
ALTER COLUMN "horaProgramadaSalida" DROP NOT NULL,
ALTER COLUMN "horaEntrada" DROP NOT NULL,
ALTER COLUMN "horaSalida" DROP NOT NULL,
ALTER COLUMN "llegadaTarde" DROP NOT NULL,
ALTER COLUMN "cantidadHorasExtrasDiurnas" DROP NOT NULL,
ALTER COLUMN "cantidadHorasExtrasNocturnas" DROP NOT NULL,
ALTER COLUMN "cantidadHorasExtrasDiurnasDominicalFestiva" DROP NOT NULL,
ALTER COLUMN "cantidadHorasExtrasNocturnasDominicalFestiva" DROP NOT NULL,
ALTER COLUMN "cantidadHorasRecargoNocturno" DROP NOT NULL,
ALTER COLUMN "cantidadHorasRecargoDiurnoDominicalFestivo" DROP NOT NULL,
ALTER COLUMN "cantidadHorasRecargoNocturnoDominicalFestivo" DROP NOT NULL;

-- AlterTable
ALTER TABLE "LiquidacionesNomina" ALTER COLUMN "mes" DROP NOT NULL,
ALTER COLUMN "quincena" DROP NOT NULL,
ALTER COLUMN "salarioBase" DROP NOT NULL,
ALTER COLUMN "valorHora" DROP NOT NULL,
ALTER COLUMN "horasLaboradas" DROP NOT NULL,
ALTER COLUMN "baseLiquidacion" DROP NOT NULL,
ALTER COLUMN "auxilioTransporte" DROP NOT NULL,
ALTER COLUMN "horasIncapacidad" DROP NOT NULL,
ALTER COLUMN "pagoIncapacidad" DROP NOT NULL,
ALTER COLUMN "cantidadHorasExtrasDiurnas" DROP NOT NULL,
ALTER COLUMN "valorHorasExtrasDiurnas" DROP NOT NULL,
ALTER COLUMN "cantidadHorasExtrasNocturnas" DROP NOT NULL,
ALTER COLUMN "valorHorasExtrasNocturnas" DROP NOT NULL,
ALTER COLUMN "cantidadHorasExtrasDiurnasDominicalFestiva" DROP NOT NULL,
ALTER COLUMN "valorHorasExtrasDiurnasDominicalFestiva" DROP NOT NULL,
ALTER COLUMN "cantidadHorasExtrasNocturnasDominicalFestiva" DROP NOT NULL,
ALTER COLUMN "valorHorasExtrasNocturnasDominicalFestiva" DROP NOT NULL,
ALTER COLUMN "cantidadHorasRecargoNocturno" DROP NOT NULL,
ALTER COLUMN "valorHorasRecargoNocturno" DROP NOT NULL,
ALTER COLUMN "cantidadHorasRecargoDiurnoDominicalFestivo" DROP NOT NULL,
ALTER COLUMN "valorHorasRecargoDiurnoDominicalFestivo" DROP NOT NULL,
ALTER COLUMN "cantidadHorasRecargoNocturnoDominicalFestivo" DROP NOT NULL,
ALTER COLUMN "valorHorasRecargoNocturnoDominicalFestivo" DROP NOT NULL,
ALTER COLUMN "productividad" DROP NOT NULL,
ALTER COLUMN "bonificaciones" DROP NOT NULL,
ALTER COLUMN "asistenciaTecnica" DROP NOT NULL,
ALTER COLUMN "totalDevengado" DROP NOT NULL,
ALTER COLUMN "salud" DROP NOT NULL,
ALTER COLUMN "pension" DROP NOT NULL,
ALTER COLUMN "deducciones" DROP NOT NULL,
ALTER COLUMN "netoPagado" DROP NOT NULL,
ALTER COLUMN "aportesAlColaborador" DROP NOT NULL,
ALTER COLUMN "seguroVida" DROP NOT NULL,
ALTER COLUMN "retenciones" DROP NOT NULL,
ALTER COLUMN "vacaciones" DROP NOT NULL,
ALTER COLUMN "cesantias" DROP NOT NULL,
ALTER COLUMN "prima" DROP NOT NULL,
ALTER COLUMN "totalPagar" DROP NOT NULL;
